In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder

In [2]:
main_df = pd.read_csv('설문지_응답.csv')
df = main_df.iloc[:, 1:34]
df.shape

(191, 33)

In [3]:
df.columns

Index(['1. 본인의 이메일을 입력해주세요', '3. 본인의 성별을 입력하세요.', '2. 본인의 나이를 입력하세요(숫자만 입력)',
       '4. 본인의 거주 홀을 입력하세요 \n(모르시면 아무거나 입력하셔도 됩니다.)', '5. 본인의 단과대를 입력하세요',
       '6. 본인 성격 유형을 입력하세요.', '7. 본인 주말 거주 유형을 입력하세요.',
       '8. 본인 평일 거주 유형을 입력하세요.', '9. 본인 흡연 여부를 입력하세요.',
       '10. 본인의 음주 정도를 입력하세요.', '11. 본인의 식사 해결 장소를 입력하세요.',
       '12. 룸메이트와 배달 음식 같이 먹기 희망 여부를 입력하세요.', '13. 본인 평균 기상 시간을 입력하세요.',
       '14. 본인 평균 취침 시간을 입력하세요.', '15. 본인의 취침시 예민도를 입력하세요.',
       '16. 본인의 잠버릇 유무를 입력하세요.', '17. 본인의 일주일간 청소 빈도를 입력하세요.',
       '18. 본인의 샤워 시간대를 입력하세요.', '1. 원하는 룸메이트 나이대를 입력하세요.',
       '2. 룸메이트와 같은 단과대 희망 여부를 입력하세요.', '3. 원하는 룸메이트 성격 유형을 입력하세요.',
       '4. 원하는 룸메이트 주말 거주 유형을 입력하세요.', '5. 원하는 룸메이트 평일 거주 유형을 입력하세요.',
       '6. 원하는 룸메이트 흡연 여부를 입력하세요.', '7. 원하는 룸메이트 음주 정도를 입력하세요.',
       '8. 원하는 룸메이트 식사 해결 장소를 입력하세요.', '9. 원하는 룸메이트 배달 음식 같이 먹기 희망 여부를 입력하세요.',
       '10.  원하는 룸메이트 평균 기상 시간을 입력하세요.', '11. 원하는 룸메이트 평균 취침 시간을 입력하세요.',
       '12 .원하는 룸메이트 취침 예민도를 입력하세요.', '13. 원하는 룸메이트 잠버릇 유무를 입력하세요.',
       '14. 원하는 룸메이트 일주일간 청소 빈도를 입력하세요.', '15. 원하는 룸메이트 샤워 시간대를 입력하세요.'],
      dtype='object')

In [4]:
# 변경할 열이름
col_list = ['email', 'sex', 'age', 'dorm_select', 'college_of', 'personality', 'weekend_stay', 
            'weekday_stay', 'smoke', 'alchol', 'm_how_eat', 'how_eat_in', 'wake_up', 'm_sleep', 
            'sleep_sensitive', 'sleep_habit', 'clean_period', 'shower_timezone', 'w_age_range', 
            'w_diff_college_of', 'w_personality', 'w_weekend_stay', 'w_weekday_stay', 'w_smoke', 
            'w_alchol', 'w_how_eat', 'w_how_eat_in', 'w_wake_up', 'w_sleep', 'w_sleep_sensitive', 
            'w_sleep_habit', 'w_clean_period', 'w_shower_timezone']

df.columns = col_list
df.head()

,email,sex,age,dorm_select,college_of,personality,weekend_stay,weekday_stay,smoke,alchol,...,w_smoke,w_alchol,w_how_eat,w_how_eat_in,w_wake_up,w_sleep,w_sleep_sensitive,w_sleep_habit,w_clean_period,w_shower_timezone
0,lhj5561@naver.com,남자,27,레이크홀,융합과학기술원,E(외향),주로 기숙사 밖,주로 기숙사 내,비흡연자,드물게,...,비흡연,드물게,기숙사 식당,희망,상관 없음,2시 이후,둔감,없다,0회~1회,아침
1,foo@gmail.com,남자,21,레이크홀,문과대,E(외향),주로 기숙사 내,주로 기숙사 내,흡연자,자주,...,흡연,상관 없음,기숙사 식당,비희망,8시~10시,상관 없음,예민,있다,2회~4회,상관 없음
2,lazurite72@naver.com,남자,20,레이크홀,경영대,I(내향),주로 기숙사 밖,주로 기숙사 내,비흡연자,드물게,...,상관 없음,상관 없음,기숙사 밖,비희망,상관 없음,상관 없음,둔감,상관 없음,0회~1회,상관 없음
3,hsw1805@naver.com,남자,25,비레이크홀,기타,I(내향),주로 기숙사 내,주로 기숙사 내,비흡연자,드물게,...,비흡연,드물게,기숙사 밖,희망,상관 없음,상관 없음,둔감,없다,2회~4회,아침
4,sohneun22@gmail.com,여자,21,레이크홀,공과대,I(내향),주로 기숙사 밖,주로 기숙사 내,비흡연자,보통,...,비흡연,상관 없음,기숙사 밖,상관 없음,8시~10시,12시~2시,둔감,없다,상관 없음,상관 없음

In [5]:
# 나이 전처리
df.loc[df['age'] < 20, 'age'] = 20
df.loc[df['age'] > 28, 'age'] = 28

# 잘 들어갔는지 확인
df['age'].unique()

array([27, 21, 20, 25, 24, 26, 23, 28, 22])

In [6]:
# primary key인 이메일 삭제
col_list.remove('email')
print(col_list)
print(len(col_list))

# 범주형 변수만 있는 DF -> 사실상 전체 DF
df_cat = df[col_list].copy()         # 문자열로 저장된 DF
df_label = df[col_list].copy()       # 라벨 인코딩 된 DF

['sex', 'age', 'dorm_select', 'college_of', 'personality', 'weekend_stay', 'weekday_stay', 'smoke', 'alchol', 'm_how_eat', 'how_eat_in', 'wake_up', 'm_sleep', 'sleep_sensitive', 'sleep_habit', 'clean_period', 'shower_timezone', 'w_age_range', 'w_diff_college_of', 'w_personality', 'w_weekend_stay', 'w_weekday_stay', 'w_smoke', 'w_alchol', 'w_how_eat', 'w_how_eat_in', 'w_wake_up', 'w_sleep', 'w_sleep_sensitive', 'w_sleep_habit', 'w_clean_period', 'w_shower_timezone']
32

In [7]:
df_label['age'] = df_label['age']%10
df_cat['age'] = df_cat['age']%10

In [8]:
# 상관없음 전처리
replace_dict = {'상관 없음': '0'}
df_label.replace(replace_dict, inplace=True)

In [9]:
df_label

,sex,age,dorm_select,college_of,personality,weekend_stay,weekday_stay,smoke,alchol,m_how_eat,...,w_smoke,w_alchol,w_how_eat,w_how_eat_in,w_wake_up,w_sleep,w_sleep_sensitive,w_sleep_habit,w_clean_period,w_shower_timezone
0,남자,7,레이크홀,융합과학기술원,E(외향),주로 기숙사 밖,주로 기숙사 내,비흡연자,드물게,기숙사 식당,...,비흡연,드물게,기숙사 식당,희망,0,2시 이후,둔감,없다,0회~1회,아침
1,남자,1,레이크홀,문과대,E(외향),주로 기숙사 내,주로 기숙사 내,흡연자,자주,기숙사 내,...,흡연,0,기숙사 식당,비희망,8시~10시,0,예민,있다,2회~4회,0
2,남자,0,레이크홀,경영대,I(내향),주로 기숙사 밖,주로 기숙사 내,비흡연자,드물게,기숙사 밖,...,0,0,기숙사 밖,비희망,0,0,둔감,0,0회~1회,0
3,남자,5,비레이크홀,기타,I(내향),주로 기숙사 내,주로 기숙사 내,비흡연자,드물게,기숙사 내,...,비흡연,드물게,기숙사 밖,희망,0,0,둔감,없다,2회~4회,아침
4,여자,1,레이크홀,공과대,I(내향),주로 기숙사 밖,주로 기숙사 내,비흡연자,보통,기숙사 밖,...,비흡연,0,기숙사 밖,0,8시~10시,12시~2시,둔감,없다,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,남자,4,비레이크홀,융합과학기술원,I(내향),주로 기숙사 내,주로 기숙사 내,비흡연자,드물게,기숙사 내,...,0,0,0,비희망,0,0,0,0,0,0
187,여자,4,레이크홀,사범대,I(내향),주로 기숙사 내,주로 기숙사 내,비흡연자,보통,기숙사 밖,...,비흡연,보통,기숙사 밖,희망,8시~10시,12시~2시,둔감,없다,2회~4회,저녁
188,남자,8,레이크홀,사회과학대,E(외향),주로 기숙사 밖,주로 기숙사 내,비흡연자,보통,기숙사 식당,...,비흡연,보통,0,희망,8시~10시,12시~2시,둔감,없다,2회~4회,0
189,남자,6,레이크홀,이과대,I(내향),주로 기숙사 내,주로 기숙사 밖,비흡연자,드물게,기숙사 식당,...,비흡연,드물게,0,0,10시~12시,2시 이후,둔감,0,2회~4회,0
190,남자,8,레이크홀,공과대,E(외향),주로 기숙사 밖,주로 기숙사 내,비흡연자,자주,기숙사 식당,...,비흡연,0,0,0,8시~10시,12시~2시,둔감,없다,2회~4회,0

In [10]:
# LabelEncoder를 객체로 생성합니다.
le = LabelEncoder()

for col in df_label.columns:
    if df_label[col].dtype == 'object':  # 오브젝트 타입의 열만 인코딩
        
        if col == 'wake_up':
            df_label.loc[df_label[col]=='6시~8시', col] = '1'
            df_label.loc[df_label[col]=='8시~10시', col] = '2'
            df_label.loc[df_label[col]=='10시~12시', col] = '3'
            df_label.loc[df_label[col]=='12시 이후', col] = '4'
        elif col == 'w_wake_up':
            df_label.loc[df_label[col]=='6시~8시', col] = '1'
            df_label.loc[df_label[col]=='8시~10시', col] = '2'
            df_label.loc[df_label[col]=='10시~12시', col] = '3'
            df_label.loc[df_label[col]=='12시 이후', col] = '4'
        
        df_label[col] = le.fit_transform(df_label[col])

df_label   # 라벨 인코딩 결과

,sex,age,dorm_select,college_of,personality,weekend_stay,weekday_stay,smoke,alchol,m_how_eat,...,w_smoke,w_alchol,w_how_eat,w_how_eat_in,w_wake_up,w_sleep,w_sleep_sensitive,w_sleep_habit,w_clean_period,w_shower_timezone
0,0,7,0,11,0,1,0,0,0,2,...,1,1,3,2,0,3,1,1,1,1
1,0,1,0,4,0,0,0,1,2,0,...,2,0,3,1,2,0,2,2,2,0
2,0,0,0,1,1,1,0,0,0,1,...,0,0,2,1,0,0,1,0,1,0
3,0,5,1,3,1,0,0,0,0,0,...,1,1,2,2,0,0,1,1,2,1
4,1,1,0,2,1,1,0,0,1,1,...,1,0,2,0,2,2,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,0,4,1,11,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
187,1,4,0,6,1,0,0,0,1,1,...,1,2,2,2,2,2,1,1,2,2
188,0,8,0,7,0,1,0,0,1,2,...,1,2,0,2,2,2,1,1,2,0
189,0,6,0,12,1,0,1,0,0,2,...,1,1,0,0,3,3,1,0,2,0
190,0,8,0,2,0,1,0,0,2,2,...,1,0,0,0,2,2,1,1,2,0

In [11]:
plus = ['sex', 'dorm_select', 'personality', 'weekend_stay', 'weekday_stay', 'smoke', 'alchol', 'm_how_eat', 'how_eat_in', 'wake_up', 'm_sleep', 'sleep_sensitive', 'sleep_habit', 'clean_period', 'shower_timezone']
print(len(plus))

df_label[plus] += 1   # want_ 정보랑 맞추기 위해서 1 더하기

15

In [12]:
df_label

,sex,age,dorm_select,college_of,personality,weekend_stay,weekday_stay,smoke,alchol,m_how_eat,...,w_smoke,w_alchol,w_how_eat,w_how_eat_in,w_wake_up,w_sleep,w_sleep_sensitive,w_sleep_habit,w_clean_period,w_shower_timezone
0,1,7,1,11,1,2,1,1,1,3,...,1,1,3,2,0,3,1,1,1,1
1,1,1,1,4,1,1,1,2,3,1,...,2,0,3,1,2,0,2,2,2,0
2,1,0,1,1,2,2,1,1,1,2,...,0,0,2,1,0,0,1,0,1,0
3,1,5,2,3,2,1,1,1,1,1,...,1,1,2,2,0,0,1,1,2,1
4,2,1,1,2,2,2,1,1,2,2,...,1,0,2,0,2,2,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,1,4,2,11,2,1,1,1,1,1,...,0,0,0,1,0,0,0,0,0,0
187,2,4,1,6,2,1,1,1,2,2,...,1,2,2,2,2,2,1,1,2,2
188,1,8,1,7,1,2,1,1,2,3,...,1,2,0,2,2,2,1,1,2,0
189,1,6,1,12,2,1,2,1,1,3,...,1,1,0,0,3,3,1,0,2,0
190,1,8,1,2,1,2,1,1,3,3,...,1,0,0,0,2,2,1,1,2,0

In [13]:
label_df = pd.concat([df['email'], df_label], axis=1)
label_df

,email,sex,age,dorm_select,college_of,personality,weekend_stay,weekday_stay,smoke,alchol,...,w_smoke,w_alchol,w_how_eat,w_how_eat_in,w_wake_up,w_sleep,w_sleep_sensitive,w_sleep_habit,w_clean_period,w_shower_timezone
0,lhj5561@naver.com,1,7,1,11,1,2,1,1,1,...,1,1,3,2,0,3,1,1,1,1
1,foo@gmail.com,1,1,1,4,1,1,1,2,3,...,2,0,3,1,2,0,2,2,2,0
2,lazurite72@naver.com,1,0,1,1,2,2,1,1,1,...,0,0,2,1,0,0,1,0,1,0
3,hsw1805@naver.com,1,5,2,3,2,1,1,1,1,...,1,1,2,2,0,0,1,1,2,1
4,sohneun22@gmail.com,2,1,1,2,2,2,1,1,2,...,1,0,2,0,2,2,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,alswo000615@gmail.com,1,4,2,11,2,1,1,1,1,...,0,0,0,1,0,0,0,0,0,0
187,최현지,2,4,1,6,2,1,1,1,2,...,1,2,2,2,2,2,1,1,2,2
188,psh1576@naver.com,1,8,1,7,1,2,1,1,2,...,1,2,0,2,2,2,1,1,2,0
189,qkr981024@naver.com,1,6,1,12,2,1,2,1,1,...,1,1,0,0,3,3,1,0,2,0
190,skyoon7899@gmail.com,1,8,1,2,1,2,1,1,3,...,1,0,0,0,2,2,1,1,2,0

In [14]:
label_df.to_csv('main_data.csv')

In [15]:
df_label.to_csv('라벨인코딩결과.csv')
df.to_csv('룸메이트_설문지결과.csv')